import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProvider from "./theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        {/**HOW TO READ Context here without making this a client component? Is it advisable to make this a client component? */}
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
